name: Set AWS EKS kubeconfig 
command: aws eks update-kubeconfig --region {{region}} --name {{cluster}} 
arguments:
  - name: region
    description: AWS region of the cluster
  - name: cluster
    description: The EKS cluster name
    

tags: ["aws", "eks", "kubeconfig"]